[package]
name = "gpui_core"
version = "0.1.1"
edition = "2021"
license = "MIT"
publish = false

[lib]
name = "gpui_core"
crate-type = ["rlib"]

[dependencies]
image = { version = "0.25.10", default-features = false, features = ["bmp", "gif", "ico", "jpeg", "png", "tiff", "webp"] }
ropey = { version = "=2.0.0-beta.1", features = ["metric_lines_lf", "metric_utf16"] }
