[package]
name = "gpui_nif"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "gpui_nif"
crate-type = ["cdylib"]

[features]
default = ["desktop"]
real-gpui = ["dep:zed_gpui", "dep:gpui_platform", "dep:image", "dep:futures", "dep:unicode-segmentation"]
desktop = ["real-gpui", "gpui_platform/font-kit", "gpui_platform/wayland", "gpui_platform/x11"]

[dependencies]
rustler = "0.38.0"
zed_gpui = { git = "https://github.com/zed-industries/zed", rev = "f16a46967b1f748003fa518609703f503e9d0d67", package = "gpui", optional = true }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "f16a46967b1f748003fa518609703f503e9d0d67", package = "gpui_platform", optional = true }
image = { version = "0.25.10", optional = true }
futures = { version = "0.3", optional = true }
unicode-segmentation = { version = "1.12", optional = true }

[patch.crates-io]
async-process = { git = "https://github.com/zed-industries/async-process.git", rev = "0b6d6713570af61806e1e5cb40e0f757cb93fd9d" }
