// This file is generated by RustQ. Do not edit by hand.

pub const GPUI_ELEMENT_TAGS: &[&str] = &["div", "button", "input", "img", "text"];
pub const GPUI_STYLE_ATTRS: &[&str] = &["display", "flex_direction", "align_items", "justify_content", "background", "color", "font_size", "gap", "padding", "margin", "width", "height", "border_radius", "border_width"];
pub const GPUI_EVENT_ATTRS: &[&str] = &["phx-click", "phx-change", "phx-keydown", "phx-keyup"];
pub const GPUI_RESOURCE_TYPES: &[&str] = &["raster", "resource_ref"];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GeneratedComponentKind {
    Container,
    Input,
    Image,
    Text,
    Unknown,
}


#[derive(Clone, Debug, Default)]
#[cfg(feature = "real-gpui")]
struct StyleAttrs {
display_flex: bool,
flex_direction: Option<String>,
align_items: Option<String>,
justify_content: Option<String>,
background: Option<u32>,
color: Option<u32>,
font_size: Option<f32>,
gap: Option<f32>,
padding: Option<f32>,
margin: Option<f32>,
width: Option<f32>,
height: Option<f32>,
border_radius: Option<f32>,
border_width: Option<f32>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GeneratedElementTag {
    Div,
    Button,
    Input,
    Img,
    Text,
    Unknown,
}

pub fn decode_generated_element_tag(tag: &str) -> GeneratedElementTag {
    match tag {
        "div" => GeneratedElementTag::Div,
        "button" => GeneratedElementTag::Button,
        "input" => GeneratedElementTag::Input,
        "img" => GeneratedElementTag::Img,
        "text" => GeneratedElementTag::Text,
        _ => GeneratedElementTag::Unknown,
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GeneratedResourceType {
    Raster,
    ResourceRef,
    Unknown,
}

pub fn decode_generated_resource_type(resource_type: &str) -> GeneratedResourceType {
    match resource_type {
        "raster" => GeneratedResourceType::Raster,
        "resource_ref" => GeneratedResourceType::ResourceRef,
        _ => GeneratedResourceType::Unknown,
    }
}

pub fn generated_event_attr_to_type(attr: &str) -> Option<&'static str> {
    match attr {
            "phx-click" => Some("click"),
            "phx-change" => Some("change"),
            "phx-keydown" => Some("keydown"),
            "phx-keyup" => Some("keyup"),
        _ => None,
    }
}

pub fn generated_component_kind(tag: GeneratedElementTag) -> GeneratedComponentKind {
    match tag {
            GeneratedElementTag::Div => GeneratedComponentKind::Container,
            GeneratedElementTag::Button => GeneratedComponentKind::Container,
            GeneratedElementTag::Input => GeneratedComponentKind::Input,
            GeneratedElementTag::Img => GeneratedComponentKind::Image,
            GeneratedElementTag::Text => GeneratedComponentKind::Text,
        GeneratedElementTag::Unknown => GeneratedComponentKind::Unknown,
    }
}

#[derive(Clone, Debug)]
#[cfg(feature = "real-gpui")]
#[allow(dead_code)]
pub(crate) struct GeneratedRaster {
pub(crate) width: u32,
pub(crate) height: u32,
pub(crate) format: String,
pub(crate) stride: Option<u32>,
pub(crate) data: Vec<u8>,
}

#[derive(Clone, Debug)]
#[cfg(feature = "real-gpui")]
#[allow(dead_code)]
pub(crate) struct GeneratedResourceRef {
pub(crate) id: String,
pub(crate) type_: String,
}

#[cfg(feature = "real-gpui")]
#[allow(dead_code)]
pub(crate) fn decode_generated_raster_resource(term: Term) -> NifResult<GeneratedRaster> {
    let env = term.get_env();
    Ok(GeneratedRaster {
        width: term.map_get(Atom::from_bytes(env, b"width")?)?.decode::<u32>()?,
        height: term.map_get(Atom::from_bytes(env, b"height")?)?.decode::<u32>()?,
        format: term
            .map_get(Atom::from_bytes(env, b"format")?)?
            .atom_to_string()
            .unwrap_or_else(|_| "rgba8".to_string()),
        stride: optional_u32(term.map_get(Atom::from_bytes(env, b"stride")?).ok()),
        data: term
            .map_get(Atom::from_bytes(env, b"data")?)?
            .decode::<rustler::Binary>()?
            .as_slice()
            .to_vec(),
    })

}

#[cfg(feature = "real-gpui")]
#[allow(dead_code)]
pub(crate) fn decode_generated_resource_ref_resource(term: Term) -> NifResult<GeneratedResourceRef> {
    let env = term.get_env();
    Ok(GeneratedResourceRef {
        id: term.map_get(Atom::from_bytes(env, b"id")?)?.decode::<String>()?,
        type_: term.map_get(Atom::from_bytes(env, b"type")?)?.atom_to_string().unwrap_or_default(),
    })

}

#[derive(Clone, Debug)]
#[cfg(feature = "real-gpui")]
pub(crate) struct GeneratedDiv {
pub(crate) style: StyleAttrs,
pub(crate) children: Vec<ElementNode>,
pub(crate) click: Option<String>,
}

#[derive(Clone, Debug)]
#[cfg(feature = "real-gpui")]
pub(crate) struct GeneratedButton {
pub(crate) style: StyleAttrs,
pub(crate) children: Vec<ElementNode>,
pub(crate) click: Option<String>,
}

#[derive(Clone, Debug)]
#[cfg(feature = "real-gpui")]
pub(crate) struct GeneratedInput {
pub(crate) style: StyleAttrs,
pub(crate) value: String,
pub(crate) placeholder: Option<String>,
pub(crate) change: Option<String>,
pub(crate) keydown: Option<String>,
pub(crate) keyup: Option<String>,
}

#[derive(Clone, Debug)]
#[cfg(feature = "real-gpui")]
pub(crate) struct GeneratedImg {
pub(crate) raster: RasterData,
}

#[derive(Clone, Debug)]
#[cfg(feature = "real-gpui")]
pub(crate) struct GeneratedText {
pub(crate) text: String,
}

#[cfg(feature = "real-gpui")]
pub(crate) fn decode_generated_div(term: Term) -> NifResult<GeneratedDiv> {
      Ok(GeneratedDiv {
          style: decode_style(term).unwrap_or_default(),
          children: decode_children(term).unwrap_or_default(),
          click: generated_string_attr(term, "phx-click"),
      })

}

#[cfg(feature = "real-gpui")]
pub(crate) fn decode_generated_button(term: Term) -> NifResult<GeneratedButton> {
      Ok(GeneratedButton {
          style: decode_style(term).unwrap_or_default(),
          children: decode_children(term).unwrap_or_default(),
          click: generated_string_attr(term, "phx-click"),
      })

}

#[cfg(feature = "real-gpui")]
pub(crate) fn decode_generated_input(term: Term) -> NifResult<GeneratedInput> {
      Ok(GeneratedInput {
          style: decode_style(term).unwrap_or_default(),
          value: generated_string_attr(term, "value").unwrap_or_default(),
          placeholder: generated_string_attr(term, "placeholder"),
          change: generated_string_attr(term, "phx-change"),
          keydown: generated_string_attr(term, "phx-keydown"),
          keyup: generated_string_attr(term, "phx-keyup"),
      })

}

#[cfg(feature = "real-gpui")]
pub(crate) fn decode_generated_img(term: Term) -> NifResult<GeneratedImg> {
      Ok(GeneratedImg {
          raster: decode_raster(term)?,
      })

}

#[cfg(feature = "real-gpui")]
pub(crate) fn decode_generated_text(term: Term) -> NifResult<GeneratedText> {
      Ok(GeneratedText {
          text: decode_text_children(term).unwrap_or_default(),
      })

}

#[cfg(feature = "real-gpui")]
pub(crate) fn apply_generated_style_attr(attrs: &mut StyleAttrs, key: &str, value: Term) {
    match key {
            "display" => attrs.display_flex = atom_eq(value, "flex"),
            "flex_direction" => attrs.flex_direction = atom_string(value),
            "align_items" => attrs.align_items = atom_string(value),
            "justify_content" => attrs.justify_content = atom_string(value),
            "background" => attrs.background = rgb_value(value),
            "color" => attrs.color = rgb_value(value),
            "font_size" => attrs.font_size = px_value(value),
            "gap" => attrs.gap = px_value(value),
            "padding" => attrs.padding = px_value(value),
            "margin" => attrs.margin = px_value(value),
            "width" => attrs.width = px_value(value),
            "height" => attrs.height = px_value(value),
            "border_radius" => attrs.border_radius = radius_value(value),
            "border_width" => attrs.border_width = px_value(value),
        _ => {}
    }

}

#[cfg(feature = "real-gpui")]
pub(crate) fn apply_generated_render_styles(element: gpui::Div, style: StyleAttrs) -> gpui::Div {
    use gpui::{px, rgb, Styled};

    let mut element = element;
    if style.display_flex {
        element = element.flex();
    }

    match style.flex_direction.as_deref() {
            Some("column") => element = element.flex_col(),
            Some("row") => element = element.flex_row(),
        _ => {}
    }

    match style.align_items.as_deref() {
            Some("center") => element = element.items_center(),
            Some("start") => element = element.items_start(),
            Some("end") => element = element.items_end(),
        _ => {}
    }

    match style.justify_content.as_deref() {
            Some("center") => element = element.justify_center(),
            Some("start") => element = element.justify_start(),
            Some("end") => element = element.justify_end(),
        _ => {}
    }

    if let Some(value) = style.background {
        element = element.bg(rgb(value));
    }

    if let Some(value) = style.color {
        element = element.text_color(rgb(value));
    }

    if let Some(value) = style.font_size {
        element = element.text_size(px(value));
    }

    if let Some(value) = style.gap {
        element = element.gap(px(value));
    }

    if let Some(value) = style.padding {
        element = element.p(px(value));
    }

    if let Some(value) = style.margin {
        element = element.m(px(value));
    }

    if let Some(value) = style.width {
        element = element.w(px(value));
    }

    if let Some(value) = style.height {
        element = element.h(px(value));
    }

    if let Some(value) = style.border_radius {
        element = element.rounded(px(value));
    }

    if let Some(value) = style.border_width {
        element = element.border(px(value));
    }

    element

}

#[cfg(feature = "real-gpui")]
pub(crate) fn apply_generated_click_event(
    element: gpui::Div,
    event: Option<String>,
    runtime: ResourceArc<RuntimeResource>,
    window_id: u64,
) -> gpui::AnyElement {
    use gpui::{InteractiveElement, IntoElement, StatefulInteractiveElement};

    if let Some(event) = event {
        let runtime_for_click = runtime.clone();
        let element_id = format!("gpui-elixir-click-{window_id}-{event}");

        element.id(element_id).on_click(move |_event, _window, _cx| {
            let _ = push_event(
                &runtime_for_click,
                NativeEvent::Click { window_id, event: event.clone() },
            );
        }).into_any_element()
    } else {
        element.into_any_element()
    }
}

#[cfg(feature = "real-gpui")]
pub(crate) fn apply_generated_input_events(
    element: gpui::Div,
    value: String,
    change: Option<String>,
    keydown: Option<String>,
    keyup: Option<String>,
    runtime: ResourceArc<RuntimeResource>,
    window_id: u64,
) -> gpui::AnyElement {
    use gpui::{InteractiveElement, IntoElement, StatefulInteractiveElement};

    let mut element = element.id(format!(
        "gpui-elixir-input-{window_id}-{}",
        change.clone().unwrap_or_default()
    ));

    if let Some(event) = change {
        let runtime_for_change = runtime.clone();
        let value_for_change = value.clone();
        element = element.on_click(move |_event, _window, _cx| {
            let _ = push_event(
                &runtime_for_change,
                NativeEvent::Input {
                    kind: "change".to_string(),
                    window_id,
                    event: event.clone(),
                    value: Some(value_for_change.clone()),
                },
            );
        });
    }

    if let Some(event) = keydown {
        let runtime_for_keydown = runtime.clone();
        element = element.on_key_down(move |key_event, _window, _cx| {
            let value = key_event
                .keystroke
                .key_char
                .clone()
                .or_else(|| Some(key_event.keystroke.key.clone()));
            let _ = push_event(
                &runtime_for_keydown,
                NativeEvent::Input {
                    kind: "keydown".to_string(),
                    window_id,
                    event: event.clone(),
                    value,
                },
            );
        });
    }

    if let Some(event) = keyup {
        let runtime_for_keyup = runtime.clone();
        element = element.on_key_up(move |key_event, _window, _cx| {
            let value = key_event
                .keystroke
                .key_char
                .clone()
                .or_else(|| Some(key_event.keystroke.key.clone()));
            let _ = push_event(
                &runtime_for_keyup,
                NativeEvent::Input {
                    kind: "keyup".to_string(),
                    window_id,
                    event: event.clone(),
                    value,
                },
            );
        });
    }

    element.into_any_element()
}


#[cfg(feature = "real-gpui")]
pub(crate) fn render_generated_text_component(text: String) -> gpui::AnyElement {
    render_generated_text_primitive(text)
}

#[cfg(feature = "real-gpui")]
pub(crate) fn render_generated_image_component(raster: RasterData) -> gpui::AnyElement {
    render_generated_image_primitive(raster)
}

#[cfg(feature = "real-gpui")]
pub(crate) fn render_generated_input_component(
    style: StyleAttrs,
    value: String,
    placeholder: Option<String>,
    change: Option<String>,
    keydown: Option<String>,
    keyup: Option<String>,
    runtime: ResourceArc<RuntimeResource>,
    window_id: u64,
) -> gpui::AnyElement {
    render_generated_input_primitive(style, value, placeholder, change, keydown, keyup, runtime, window_id)
}

#[cfg(feature = "real-gpui")]
pub(crate) fn render_generated_container_component(
    style: StyleAttrs,
    children: Vec<ElementNode>,
    click: Option<String>,
    runtime: ResourceArc<RuntimeResource>,
    window_id: u64,
) -> gpui::AnyElement {
    render_generated_container_primitive(style, children, click, runtime, window_id)
}


#[cfg(feature = "real-gpui")]
pub(crate) fn render_generated_element_node(node: ElementNode, runtime: ResourceArc<RuntimeResource>, window_id: u64) -> gpui::AnyElement {
    match node {
        ElementNode::Text(text) => render_generated_text_component(text),
        ElementNode::Image(raster) => render_generated_image_component(raster),
        ElementNode::Input { style, value, placeholder, change, keydown, keyup } => {
            render_generated_input_component(style, value, placeholder, change, keydown, keyup, runtime, window_id)
        }
        ElementNode::Div { style, children, click } => {
            render_generated_container_component(style, children, click, runtime, window_id)
        }
    }

}
