// This file is generated by RustQ. Do not edit by hand.

#[rustler::nif]
fn start_runtime<'a>(env: Env<'a>) -> NifResult<Term<'a>> {
    start_runtime_impl(env)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn open_window<'a>(
    env: Env<'a>,
    runtime: ResourceArc<RuntimeResource>,
    window: Term<'a>,
) -> NifResult<Term<'a>> {
    open_window_impl(env, runtime, window)
}
#[rustler::nif]
fn drain_events<'a>(
    env: Env<'a>,
    runtime: ResourceArc<RuntimeResource>,
) -> NifResult<Term<'a>> {
    drain_events_impl(env, runtime)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn validate_tree<'a>(env: Env<'a>, tree: Term<'a>) -> NifResult<Term<'a>> {
    validate_tree_impl(env, tree)
}
