// This file is generated by RustQ. Do not edit by hand.

pub const GPUI_ELEMENT_TAGS: &[&str] = &["div", "button", "input", "img", "text"];
pub const GPUI_STYLE_ATTRS: &[&str] = &["display", "flex_direction", "align_items", "justify_content", "background", "color", "font_size", "gap", "padding", "margin", "width", "height", "border_radius", "border_width"];
pub const GPUI_EVENT_ATTRS: &[&str] = &["phx-click", "phx-change", "phx-keydown", "phx-keyup"];
pub const GPUI_RESOURCE_TYPES: &[&str] = &["raster", "resource_ref"];
