defmodule GPUI.Codegen do
  @moduledoc false

  alias RustQ.Rust

  @spec generated_native_element_schema() :: String.t()
  def generated_native_element_schema do
    components = GPUI.ComponentSpec.components()
    elements = GPUI.ComponentSpec.tags()
    style_specs = GPUI.ComponentSpec.style_specs()
    styles = GPUI.ComponentSpec.styles()
    events = GPUI.ComponentSpec.events()
    resource_specs = GPUI.ComponentSpec.resource_specs()
    resources = GPUI.ComponentSpec.resources()

    """
    // This file is generated by RustQ. Do not edit by hand.

    #{generated_string_slice_const(:GPUI_ELEMENT_TAGS, elements)}
    #{generated_string_slice_const(:GPUI_STYLE_ATTRS, styles)}
    #{generated_string_slice_const(:GPUI_EVENT_ATTRS, events)}
    #{generated_string_slice_const(:GPUI_RESOURCE_TYPES, resources)}

    #{generated_component_specs(components)}

    #{generated_style_module(style_specs)}

    #{generated_enum_decl(:GeneratedElementTag, elements ++ [:Unknown])}

    pub fn decode_generated_element_tag(tag: &str) -> GeneratedElementTag {
        match tag {
    #{rust_match_arms(elements, "GeneratedElementTag")}
            _ => GeneratedElementTag::Unknown,
        }
    }

    #{generated_enum_decl(:GeneratedResourceType, resources ++ [:Unknown])}

    pub fn decode_generated_resource_type(resource_type: &str) -> GeneratedResourceType {
        match resource_type {
    #{rust_match_arms(resources, "GeneratedResourceType")}
            _ => GeneratedResourceType::Unknown,
        }
    }

    pub fn generated_event_attr_to_type(attr: &str) -> Option<&'static str> {
        match attr {
    #{rust_event_match_arms(components)}
            _ => None,
        }
    }

    pub fn generated_component_kind(tag: GeneratedElementTag) -> GeneratedComponentKind {
        match tag {
    #{rust_component_kind_arms(components)}
            GeneratedElementTag::Unknown => GeneratedComponentKind::Unknown,
        }
    }

    #{generated_resource_module(resource_specs)}

    #{generated_event_module(components)}

    #{generated_component_module(components)}
    """
  end

  @spec generated_host_commands() :: String.t()
  def generated_host_commands do
    """
    // This file is generated by RustQ. Do not edit by hand.

    #{generated_structs_and_decoders()}

    pub fn dispatch_host_command(op: &str, payload: &Term) -> Term {
        match op {
    #{generated_dispatch_arms()}
            _ => error_reply(format!("unsupported_op:{op}")),
        }
    }
    """
  end

  defp generated_dispatch_arms do
    GPUI.CommandSpec.host_commands()
    |> Enum.map_join("\n", fn {name, spec} ->
      handler = "handle_#{name}"
      decoder = "decode_#{name}"

      if Keyword.get(spec, :args, []) == [] do
        "        \"#{name}\" => #{handler}(),"
      else
        "        \"#{name}\" => match #{decoder}(payload) { Ok(command) => #{handler}(command), Err(reason) => error_reply(reason) },"
      end
    end)
  end

  defp generated_structs_and_decoders do
    GPUI.CommandSpec.host_commands()
    |> Enum.reject(fn {_name, spec} -> Keyword.get(spec, :args, []) == [] end)
    |> Enum.map_join("\n\n", fn {name, spec} ->
      struct_name = rust_struct_name(name)
      fields = Keyword.fetch!(spec, :args)

      field_defs =
        fields
        |> Enum.map_join("\n", fn {field, _type} -> "    pub #{field}: &'a Term," end)

      field_inits =
        fields
        |> Enum.map_join("\n", fn {field, _type} ->
          "        #{field}: required_payload(payload, \"#{field}\")?,"
        end)

      """
      pub struct #{struct_name}<'a> {
      #{field_defs}
      }

      pub fn decode_#{name}<'a>(payload: &'a Term) -> Result<#{struct_name}<'a>, String> {
          Ok(#{struct_name} {
      #{field_inits}
          })
      }
      """
    end)
  end

  defp generated_style_module(style_specs) do
    """
    #[cfg(feature = "real-gpui")]
    pub(crate) mod generated_styles {
        use super::*;

    #{indent_generated(generated_style_struct(style_specs))}

    #{indent_generated(generated_apply_style_function(style_specs))}

    #{indent_generated(generated_apply_render_style_function(style_specs))}
    }

    #[cfg(feature = "real-gpui")]
    pub(crate) use generated_styles::{apply_generated_render_styles, apply_generated_style_attr, StyleAttrs};
    """
  end

  defp generated_resource_module(resource_specs) do
    """
    #[cfg(feature = "real-gpui")]
    pub(crate) mod generated_resources {
        use super::*;

    #{indent_generated(generated_decoded_resource_structs(resource_specs))}

    #{indent_generated(generated_decode_resource_functions(resource_specs))}
    }

    #[cfg(feature = "real-gpui")]
    pub(crate) use generated_resources::{decode_generated_raster_resource, decode_generated_resource_ref_resource, GeneratedRaster};
    """
  end

  defp generated_event_module(components) do
    """
    #[cfg(feature = "real-gpui")]
    pub(crate) mod generated_events {
        use super::*;

    #{indent_generated(generated_event_applicators(components))}
    }

    #[cfg(feature = "real-gpui")]
    pub(crate) use generated_events::{apply_generated_click_event, apply_generated_input_events};
    """
  end

  defp generated_component_module(components) do
    """
    #[cfg(feature = "real-gpui")]
    pub(crate) mod generated_components {
        use super::*;

    #{indent_generated(generated_decoded_component_structs(components))}

    #{indent_generated(generated_decode_component_functions(components))}

    #{indent_generated(generated_decode_element_dispatch(components))}

    #{indent_generated(generated_primitive_render_contracts(components))}

    #{indent_generated(generated_render_dispatch())}
    }

    #[cfg(feature = "real-gpui")]
    pub(crate) use generated_components::{decode_generated_element_node, render_generated_element_node};
    """
  end

  defp indent_generated(code) do
    code
    |> String.trim_trailing()
    |> String.split("\n")
    |> Enum.map_join("\n", &["    ", &1])
  end

  defp generated_style_struct(style_specs) do
    Rust.struct(:StyleAttrs,
      vis: :crate,
      derive: [:Clone, :Debug, :Default],
      attrs: [~s|cfg(feature = "real-gpui")|],
      fields:
        Enum.map(style_specs, fn spec ->
          Rust.field(spec.field, rust_style_type(spec.type), vis: :crate)
        end)
    )
    |> Rust.to_fragment()
  end

  defp rust_style_type({:atom_eq, _expected}), do: "bool"
  defp rust_style_type(:atom_string), do: "Option<String>"
  defp rust_style_type(:rgb), do: "Option<u32>"
  defp rust_style_type(:px), do: "Option<f32>"
  defp rust_style_type(:radius), do: "Option<f32>"

  defp generated_decoded_resource_structs(resource_specs) do
    resource_specs
    |> Enum.map_join("\n\n", fn resource ->
      resource.name
      |> generated_resource_struct_name()
      |> Rust.struct(
        vis: :crate,
        derive: [:Clone, :Debug],
        attrs: [~s|cfg(feature = "real-gpui")|, "allow(dead_code)"],
        fields:
          Enum.map(resource.fields, fn {field, type} ->
            Rust.field(rust_field_name(field), rust_resource_type(type), vis: :crate)
          end)
      )
      |> Rust.to_fragment()
    end)
  end

  defp generated_decode_resource_functions(resource_specs) do
    resource_specs
    |> Enum.map_join("\n\n", fn resource ->
      struct_name = generated_resource_struct_name(resource.name)
      function_name = "decode_generated_#{resource.name}_resource"

      function_name
      |> Rust.fn_(
        vis: :crate,
        attrs: [~s|cfg(feature = "real-gpui")|, "allow(dead_code)"],
        args: [{:term, "Term"}],
        returns: "NifResult<#{struct_name}>",
        body: generated_decode_resource_body(resource, struct_name)
      )
      |> Rust.to_fragment()
    end)
  end

  defp generated_decode_resource_body(%{name: :raster}, struct_name) do
    """
        let env = term.get_env();
        Ok(#{struct_name} {
            width: term.map_get(Atom::from_bytes(env, b\"width\")?)?.decode::<u32>()?,
            height: term.map_get(Atom::from_bytes(env, b\"height\")?)?.decode::<u32>()?,
            format: term
                .map_get(Atom::from_bytes(env, b\"format\")?)?
                .atom_to_string()
                .unwrap_or_else(|_| \"rgba8\".to_string()),
            stride: optional_u32(term.map_get(Atom::from_bytes(env, b\"stride\")?).ok()),
            data: term
                .map_get(Atom::from_bytes(env, b\"data\")?)?
                .decode::<rustler::Binary>()?
                .as_slice()
                .to_vec(),
        })
    """
  end

  defp generated_decode_resource_body(%{name: :resource_ref}, struct_name) do
    """
        let env = term.get_env();
        Ok(#{struct_name} {
            id: term.map_get(Atom::from_bytes(env, b\"id\")?)?.decode::<String>()?,
            type_: term.map_get(Atom::from_bytes(env, b\"type\")?)?.atom_to_string().unwrap_or_default(),
        })
    """
  end

  defp rust_field_name(:type), do: :type_
  defp rust_field_name(field), do: field

  defp rust_resource_type(:u32), do: "u32"
  defp rust_resource_type(:string), do: "String"
  defp rust_resource_type(:binary), do: "Vec<u8>"

  defp rust_resource_type(:atom), do: "String"
  defp rust_resource_type({:option, :u32}), do: "Option<u32>"

  defp generated_resource_struct_name(name), do: "Generated#{Macro.camelize(to_string(name))}"

  defp generated_decoded_component_structs(components) do
    components
    |> Enum.map_join("\n\n", fn component ->
      component.tag
      |> generated_struct_name()
      |> Rust.struct(
        vis: :crate,
        derive: [:Clone, :Debug],
        attrs: [~s|cfg(feature = "real-gpui")|],
        fields: generated_struct_fields(component)
      )
      |> Rust.to_fragment()
    end)
  end

  defp generated_struct_fields(%{kind: :container}) do
    [
      Rust.field(:style, "StyleAttrs", vis: :crate),
      Rust.field(:children, "Vec<ElementNode>", vis: :crate),
      Rust.field(:click, "Option<String>", vis: :crate)
    ]
  end

  defp generated_struct_fields(%{kind: :input}) do
    [
      Rust.field(:style, "StyleAttrs", vis: :crate),
      Rust.field(:value, "String", vis: :crate),
      Rust.field(:placeholder, "Option<String>", vis: :crate),
      Rust.field(:change, "Option<String>", vis: :crate),
      Rust.field(:keydown, "Option<String>", vis: :crate),
      Rust.field(:keyup, "Option<String>", vis: :crate)
    ]
  end

  defp generated_struct_fields(%{kind: :image}) do
    [Rust.field(:raster, "ImageData", vis: :crate)]
  end

  defp generated_struct_fields(%{kind: :text}) do
    [Rust.field(:text, "String", vis: :crate)]
  end

  defp generated_decode_component_functions(components) do
    components
    |> Enum.map_join("\n\n", fn component ->
      struct_name = generated_struct_name(component.tag)
      function_name = "decode_generated_#{component.tag}"

      function_name
      |> Rust.fn_(
        vis: :crate,
        attrs: [~s|cfg(feature = "real-gpui")|],
        args: [{:term, "Term"}],
        returns: "NifResult<#{struct_name}>",
        body: generated_decode_body(component, struct_name)
      )
      |> Rust.to_fragment()
    end)
  end

  defp generated_decode_body(%{kind: :container, events: events}, struct_name) do
    click_attr = Keyword.get(events, :click, :"phx-click")

    """
          Ok(#{struct_name} {
              style: decode_style(term).unwrap_or_default(),
              children: decode_children(term).unwrap_or_default(),
              click: generated_string_attr(term, \"#{click_attr}\"),
          })
    """
  end

  defp generated_decode_body(%{kind: :input, events: events}, struct_name) do
    """
          Ok(#{struct_name} {
              style: decode_style(term).unwrap_or_default(),
              value: generated_string_attr(term, \"value\").unwrap_or_default(),
              placeholder: generated_string_attr(term, \"placeholder\"),
              change: generated_string_attr(term, \"#{Keyword.fetch!(events, :change)}\"),
              keydown: generated_string_attr(term, \"#{Keyword.fetch!(events, :keydown)}\"),
              keyup: generated_string_attr(term, \"#{Keyword.fetch!(events, :keyup)}\"),
          })
    """
  end

  defp generated_decode_body(%{kind: :image}, struct_name) do
    """
          Ok(#{struct_name} {
              raster: decode_raster(term)?,
          })
    """
  end

  defp generated_decode_body(%{kind: :text}, struct_name) do
    """
          Ok(#{struct_name} {
              text: decode_text_children(term).unwrap_or_default(),
          })
    """
  end

  defp generated_decode_element_dispatch(components) do
    Rust.fn_(:decode_generated_element_node,
      vis: :crate,
      attrs: [~s|cfg(feature = "real-gpui")|],
      args: [{:tag, "GeneratedElementTag"}, {:term, "Term"}],
      returns: "NifResult<ElementNode>",
      body: """
          match tag {
      #{rust_decode_element_arms(components)}
              GeneratedElementTag::Unknown => Ok(ElementNode::Text(String::new())),
          }
      """
    )
    |> Rust.to_fragment()
  end

  defp rust_decode_element_arms(components) do
    Enum.map_join(components, "\n", fn component ->
      variant = rust_variant(component.tag)
      decoder = "decode_generated_#{component.tag}"
      rust_decode_element_arm(component.kind, variant, decoder)
    end)
  end

  defp rust_decode_element_arm(:container, variant, decoder) do
    rust_arm(
      "GeneratedElementTag::#{variant}",
      "#{decoder}(term).map(|node| ElementNode::Div { style: node.style, children: node.children, click: node.click })"
    )
  end

  defp rust_decode_element_arm(:input, variant, decoder) do
    rust_arm(
      "GeneratedElementTag::#{variant}",
      "#{decoder}(term).map(|node| ElementNode::Input { style: node.style, value: node.value, placeholder: node.placeholder, change: node.change, keydown: node.keydown, keyup: node.keyup })"
    )
  end

  defp rust_decode_element_arm(:image, variant, decoder) do
    rust_arm(
      "GeneratedElementTag::#{variant}",
      "#{decoder}(term).map(|node| ElementNode::Image(node.raster))"
    )
  end

  defp rust_decode_element_arm(:text, variant, decoder) do
    rust_arm(
      "GeneratedElementTag::#{variant}",
      "#{decoder}(term).map(|node| ElementNode::Text(node.text))"
    )
  end

  defp generated_apply_render_style_function(style_specs) do
    Rust.fn_(:apply_generated_render_styles,
      vis: :crate,
      attrs: [~s|cfg(feature = "real-gpui")|],
      args: [{:element, "gpui::Div"}, {:style, "StyleAttrs"}],
      returns: "gpui::Div",
      body: """
          use gpui::{px, rgb, Styled};

          let mut element = element;
      #{rust_render_style_statements(style_specs)}
          element
      """
    )
    |> Rust.to_fragment()
  end

  defp rust_render_style_statements(style_specs) do
    style_specs
    |> Enum.reject(&is_nil(&1.render))
    |> Enum.map_join("\n", &rust_render_style_statement/1)
  end

  defp rust_render_style_statement(%{field: field, render: :flex_if_true}) do
    """
        if style.#{field} {
            element = element.flex();
        }
    """
  end

  defp rust_render_style_statement(%{field: field, render: {:enum_methods, values}}) do
    arms =
      values
      |> Enum.map_join("\n", fn {value, method} ->
        rust_arm(~s|Some("#{value}")|, "element = element.#{method}()")
      end)

    """
        match style.#{field}.as_deref() {
    #{arms}
            _ => {}
        }
    """
  end

  defp rust_render_style_statement(%{field: field, render: {:option_method, method, :rgb}}) do
    """
        if let Some(value) = style.#{field} {
            element = element.#{method}(rgb(value));
        }
    """
  end

  defp rust_render_style_statement(%{field: field, render: {:option_method, method, :px}}) do
    """
        if let Some(value) = style.#{field} {
            element = element.#{method}(px(value));
        }
    """
  end

  defp generated_event_applicators(_components) do
    rust_template!("generated_events.rs")
  end

  defp generated_primitive_render_contracts(_components) do
    rust_template!("generated_component_contracts.rs")
  end

  defp generated_render_dispatch do
    Rust.fn_(:render_generated_element_node,
      vis: :crate,
      attrs: [~s|cfg(feature = "real-gpui")|],
      args: [
        {:node, "ElementNode"},
        {:runtime, "ResourceArc<RuntimeResource>"},
        {:window_id, "u64"}
      ],
      returns: "gpui::AnyElement",
      body: """
          match node {
              ElementNode::Text(text) => render_generated_text_component(text),
              ElementNode::Image(raster) => render_generated_image_component(raster, runtime),
              ElementNode::Input { style, value, placeholder, change, keydown, keyup } => {
                  render_generated_input_component(style, value, placeholder, change, keydown, keyup, runtime, window_id)
              }
              ElementNode::Div { style, children, click } => {
                  render_generated_container_component(style, children, click, runtime, window_id)
              }
          }
      """
    )
    |> Rust.to_fragment()
  end

  defp generated_apply_style_function(style_specs) do
    Rust.fn_(:apply_generated_style_attr,
      vis: :crate,
      attrs: [~s|cfg(feature = "real-gpui")|],
      args: [{:attrs, "&mut StyleAttrs"}, {:key, "&str"}, {:value, "Term"}],
      body: """
          match key {
      #{rust_style_apply_arms(style_specs)}
              _ => {}
          }
      """
    )
    |> Rust.to_fragment()
  end

  defp rust_style_apply_arms(style_specs) do
    Enum.map_join(style_specs, "\n", fn spec ->
      rust_arm(~s|"#{spec.name}"|, rust_style_assignment(spec.field, spec.type))
    end)
  end

  defp rust_style_assignment(field, {:atom_eq, expected}) do
    "attrs.#{field} = atom_eq(value, \"#{expected}\")"
  end

  defp rust_style_assignment(field, :atom_string), do: "attrs.#{field} = atom_string(value)"
  defp rust_style_assignment(field, :rgb), do: "attrs.#{field} = rgb_value(value)"
  defp rust_style_assignment(field, :px), do: "attrs.#{field} = px_value(value)"
  defp rust_style_assignment(field, :radius), do: "attrs.#{field} = radius_value(value)"

  defp generated_struct_name(tag), do: "Generated#{Macro.camelize(to_string(tag))}"

  defp generated_component_specs(components) do
    kinds = components |> Enum.map(& &1.kind) |> Enum.uniq()
    generated_enum_decl(:GeneratedComponentKind, kinds ++ [:Unknown])
  end

  defp rust_event_match_arms(components) do
    components
    |> Enum.flat_map(& &1.events)
    |> Enum.uniq_by(fn {_event_type, attr} -> attr end)
    |> Enum.map_join("\n", fn {event_type, attr} ->
      rust_arm(~s|"#{attr}"|, ~s|Some("#{event_type}")|)
    end)
  end

  defp rust_component_kind_arms(components) do
    components
    |> Enum.map_join("\n", fn component ->
      rust_arm(
        "GeneratedElementTag::#{rust_variant(component.tag)}",
        "GeneratedComponentKind::#{rust_variant(component.kind)}"
      )
    end)
  end

  defp rust_template!(name) do
    [__DIR__, "..", "..", "priv", "rustq", "native", name]
    |> Path.join()
    |> Path.expand()
    |> File.read!()
  end

  defp generated_string_slice_const(name, values) do
    Rust.const(name, "&[&str]", ["&[", Enum.map_join(values, ", ", &inspect(to_string(&1))), "]"],
      vis: :pub
    )
    |> Rust.to_fragment()
  end

  defp generated_enum_decl(name, variants) do
    Rust.enum(name,
      derive: [:Clone, :Copy, :Debug, :Eq, :PartialEq],
      variants: Enum.map(variants, &rust_variant/1),
      vis: :pub
    )
    |> Rust.to_fragment()
  end

  defp rust_match_arms(values, enum_name) do
    values
    |> Enum.map_join("\n", fn value ->
      rust_arm(~s|"#{value}"|, "#{enum_name}::#{rust_variant(value)}")
    end)
  end

  defp rust_arm(pattern, body) do
    pattern
    |> Rust.arm(body)
    |> Rust.to_fragment()
  end

  defp rust_variant(value), do: value |> Atom.to_string() |> Macro.camelize()

  defp rust_struct_name(name) do
    name
    |> Atom.to_string()
    |> Macro.camelize()
    |> Kernel.<>("Command")
  end
end
