defmodule GPUI.Codegen do
  @moduledoc false

  @spec generated_native_element_schema() :: String.t()
  def generated_native_element_schema do
    elements = [:div, :button, :input, :img, :text]

    styles = [
      :display,
      :flex_direction,
      :align_items,
      :justify_content,
      :background,
      :color,
      :font_size,
      :gap,
      :padding,
      :margin,
      :width,
      :height,
      :border_radius,
      :border_width
    ]

    events = [:"phx-click", :"phx-change", :"phx-keydown", :"phx-keyup"]
    resources = [:raster, :resource_ref]

    """
    // This file is generated by RustQ. Do not edit by hand.

    pub const GPUI_ELEMENT_TAGS: &[&str] = &[#{rust_string_list(elements)}];
    pub const GPUI_STYLE_ATTRS: &[&str] = &[#{rust_string_list(styles)}];
    pub const GPUI_EVENT_ATTRS: &[&str] = &[#{rust_string_list(events)}];
    pub const GPUI_RESOURCE_TYPES: &[&str] = &[#{rust_string_list(resources)}];
    """
  end

  @spec generated_host_commands() :: String.t()
  def generated_host_commands do
    """
    // This file is generated by RustQ. Do not edit by hand.

    #{generated_structs_and_decoders()}

    pub fn dispatch_host_command(op: &str, payload: &Term) -> Term {
        match op {
    #{generated_dispatch_arms()}
            _ => error_reply(format!("unsupported_op:{op}")),
        }
    }
    """
  end

  defp generated_dispatch_arms do
    GPUI.CommandSpec.host_commands()
    |> Enum.map_join("\n", fn {name, spec} ->
      handler = "handle_#{name}"
      decoder = "decode_#{name}"

      if Keyword.get(spec, :args, []) == [] do
        "        \"#{name}\" => #{handler}(),"
      else
        "        \"#{name}\" => match #{decoder}(payload) { Ok(command) => #{handler}(command), Err(reason) => error_reply(reason) },"
      end
    end)
  end

  defp generated_structs_and_decoders do
    GPUI.CommandSpec.host_commands()
    |> Enum.reject(fn {_name, spec} -> Keyword.get(spec, :args, []) == [] end)
    |> Enum.map_join("\n\n", fn {name, spec} ->
      struct_name = rust_struct_name(name)
      fields = Keyword.fetch!(spec, :args)

      field_defs =
        fields
        |> Enum.map_join("\n", fn {field, _type} -> "    pub #{field}: &'a Term," end)

      field_inits =
        fields
        |> Enum.map_join("\n", fn {field, _type} ->
          "        #{field}: required_payload(payload, \"#{field}\")?,"
        end)

      """
      pub struct #{struct_name}<'a> {
      #{field_defs}
      }

      pub fn decode_#{name}<'a>(payload: &'a Term) -> Result<#{struct_name}<'a>, String> {
          Ok(#{struct_name} {
      #{field_inits}
          })
      }
      """
    end)
  end

  defp rust_string_list(values) do
    values
    |> Enum.map_join(", ", fn value -> ~s("#{value}") end)
  end

  defp rust_struct_name(name) do
    name
    |> Atom.to_string()
    |> Macro.camelize()
    |> Kernel.<>("Command")
  end
end
