defmodule GPUI.Schema.Core do
  @moduledoc "Neutral primitive declarations included by every native host."
  @behaviour GPUI.Schema.Provider
  @components [
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [],
      children: true,
      events: [],
      extension: nil,
      kind: :viewport,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :viewport
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        window_control: {:enum, ["drag", "close", "maximize", "minimize"]},
        accessibility_role:
          {:enum,
           [
             "button",
             "checkbox",
             "dialog",
             "group",
             "heading",
             "image",
             "label",
             "link",
             "list",
             "list_item",
             "progress",
             "radio",
             "slider",
             "splitter",
             "switch",
             "tab",
             "tab_list",
             "tab_panel",
             "text",
             "textbox",
             "tree",
             "tree_item"
           ]},
        accessibility_label: :accessibility_label,
        accessibility_description: :accessibility_description,
        accessibility_value: :accessibility_value,
        accessibility_selected: :boolean,
        accessibility_expanded: :boolean,
        accessibility_checked: :accessibility_checked,
        accessibility_orientation: {:enum, ["horizontal", "vertical"]},
        accessibility_disabled: :boolean,
        id: :string,
        motion_request: {:default, :non_negative_integer, 0},
        motion_duration: {:default, :positive_integer, 180},
        motion_delay: {:default, :non_negative_integer, 0},
        motion_easing:
          {:default, {:enum, ["linear", "ease_in", "ease_out", "ease_in_out"]}, "ease_out"},
        motion_policy: {:default, {:enum, ["respect_system", "disabled"]}, "respect_system"},
        motion_from_opacity: {:default, :number, 1.0},
        motion_from_x: {:default, :number, 0.0},
        motion_from_y: {:default, :number, 0.0}
      ],
      children: false,
      events: [click: :"phx-click", bounds: :"phx-bounds-change"],
      extension: nil,
      kind: :container,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :div
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        window_control: {:enum, ["drag", "close", "maximize", "minimize"]},
        accessibility_role:
          {:enum,
           [
             "button",
             "checkbox",
             "dialog",
             "group",
             "heading",
             "image",
             "label",
             "link",
             "list",
             "list_item",
             "progress",
             "radio",
             "slider",
             "splitter",
             "switch",
             "tab",
             "tab_list",
             "tab_panel",
             "text",
             "textbox",
             "tree",
             "tree_item"
           ]},
        accessibility_label: :accessibility_label,
        accessibility_description: :accessibility_description,
        accessibility_value: :accessibility_value,
        accessibility_selected: :boolean,
        accessibility_expanded: :boolean,
        accessibility_checked: :accessibility_checked,
        accessibility_orientation: {:enum, ["horizontal", "vertical"]},
        accessibility_disabled: :boolean,
        id: :string,
        motion_request: {:default, :non_negative_integer, 0},
        motion_duration: {:default, :positive_integer, 180},
        motion_delay: {:default, :non_negative_integer, 0},
        motion_easing:
          {:default, {:enum, ["linear", "ease_in", "ease_out", "ease_in_out"]}, "ease_out"},
        motion_policy: {:default, {:enum, ["respect_system", "disabled"]}, "respect_system"},
        motion_from_opacity: {:default, :number, 1.0},
        motion_from_x: {:default, :number, 0.0},
        motion_from_y: {:default, :number, 0.0},
        focus_request: {:default, :non_negative_integer, 0}
      ],
      children: false,
      events: [
        click: :"phx-click",
        bounds: :"phx-bounds-change",
        focus: :"phx-focus",
        blur: :"phx-blur"
      ],
      extension: nil,
      kind: :container,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :button
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :required_string,
        anchor:
          {:default,
           {:enum,
            [
              "top_left",
              "top_center",
              "top_right",
              "bottom_left",
              "bottom_center",
              "bottom_right",
              "left_center",
              "right_center"
            ]}, "top_left"},
        position_mode: {:default, {:enum, ["local", "window"]}, "local"},
        position_x: :number,
        position_y: :number,
        offset_x: {:default, :number, 0.0},
        offset_y: {:default, :number, 0.0},
        fit:
          {:default, {:enum, ["switch_anchor", "snap_to_window", "snap_with_margin"]},
           "switch_anchor"},
        margin: {:default, :non_negative_number, 0.0},
        priority: {:default, :layer_priority, 0}
      ],
      children: true,
      events: [],
      extension: nil,
      kind: :anchored_layer,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :layer
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        window_control: {:enum, ["drag", "close", "maximize", "minimize"]},
        accessibility_role:
          {:enum,
           [
             "button",
             "checkbox",
             "dialog",
             "group",
             "heading",
             "image",
             "label",
             "link",
             "list",
             "list_item",
             "progress",
             "radio",
             "slider",
             "splitter",
             "switch",
             "tab",
             "tab_list",
             "tab_panel",
             "text",
             "textbox",
             "tree",
             "tree_item"
           ]},
        accessibility_label: :accessibility_label,
        accessibility_description: :accessibility_description,
        accessibility_value: :accessibility_value,
        accessibility_selected: :boolean,
        accessibility_expanded: :boolean,
        accessibility_checked: :accessibility_checked,
        accessibility_orientation: {:enum, ["horizontal", "vertical"]},
        accessibility_disabled: :boolean,
        id: :string,
        motion_request: {:default, :non_negative_integer, 0},
        motion_duration: {:default, :positive_integer, 180},
        motion_delay: {:default, :non_negative_integer, 0},
        motion_easing:
          {:default, {:enum, ["linear", "ease_in", "ease_out", "ease_in_out"]}, "ease_out"},
        motion_policy: {:default, {:enum, ["respect_system", "disabled"]}, "respect_system"},
        motion_from_opacity: {:default, :number, 1.0},
        motion_from_x: {:default, :number, 0.0},
        motion_from_y: {:default, :number, 0.0}
      ],
      children: false,
      events: [click: :"phx-click", bounds: :"phx-bounds-change"],
      extension: nil,
      kind: :container,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :span
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        window_control: {:enum, ["drag", "close", "maximize", "minimize"]},
        accessibility_role:
          {:enum,
           [
             "button",
             "checkbox",
             "dialog",
             "group",
             "heading",
             "image",
             "label",
             "link",
             "list",
             "list_item",
             "progress",
             "radio",
             "slider",
             "splitter",
             "switch",
             "tab",
             "tab_list",
             "tab_panel",
             "text",
             "textbox",
             "tree",
             "tree_item"
           ]},
        accessibility_label: :accessibility_label,
        accessibility_description: :accessibility_description,
        accessibility_value: :accessibility_value,
        accessibility_selected: :boolean,
        accessibility_expanded: :boolean,
        accessibility_checked: :accessibility_checked,
        accessibility_orientation: {:enum, ["horizontal", "vertical"]},
        accessibility_disabled: :boolean,
        id: :string,
        motion_request: {:default, :non_negative_integer, 0},
        motion_duration: {:default, :positive_integer, 180},
        motion_delay: {:default, :non_negative_integer, 0},
        motion_easing:
          {:default, {:enum, ["linear", "ease_in", "ease_out", "ease_in_out"]}, "ease_out"},
        motion_policy: {:default, {:enum, ["respect_system", "disabled"]}, "respect_system"},
        motion_from_opacity: {:default, :number, 1.0},
        motion_from_x: {:default, :number, 0.0},
        motion_from_y: {:default, :number, 0.0}
      ],
      children: false,
      events: [click: :"phx-click", bounds: :"phx-bounds-change"],
      extension: nil,
      kind: :container,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :scroll
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        window_control: {:enum, ["drag", "close", "maximize", "minimize"]},
        accessibility_role:
          {:enum,
           [
             "button",
             "checkbox",
             "dialog",
             "group",
             "heading",
             "image",
             "label",
             "link",
             "list",
             "list_item",
             "progress",
             "radio",
             "slider",
             "splitter",
             "switch",
             "tab",
             "tab_list",
             "tab_panel",
             "text",
             "textbox",
             "tree",
             "tree_item"
           ]},
        accessibility_label: :accessibility_label,
        accessibility_description: :accessibility_description,
        accessibility_value: :accessibility_value,
        accessibility_selected: :boolean,
        accessibility_expanded: :boolean,
        accessibility_checked: :accessibility_checked,
        accessibility_orientation: {:enum, ["horizontal", "vertical"]},
        accessibility_disabled: :boolean,
        id: :string,
        motion_request: {:default, :non_negative_integer, 0},
        motion_duration: {:default, :positive_integer, 180},
        motion_delay: {:default, :non_negative_integer, 0},
        motion_easing:
          {:default, {:enum, ["linear", "ease_in", "ease_out", "ease_in_out"]}, "ease_out"},
        motion_policy: {:default, {:enum, ["respect_system", "disabled"]}, "respect_system"},
        motion_from_opacity: {:default, :number, 1.0},
        motion_from_x: {:default, :number, 0.0},
        motion_from_y: {:default, :number, 0.0}
      ],
      children: false,
      events: [click: :"phx-click", bounds: :"phx-bounds-change"],
      extension: nil,
      kind: :container,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :list
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        window_control: {:enum, ["drag", "close", "maximize", "minimize"]},
        accessibility_role:
          {:enum,
           [
             "button",
             "checkbox",
             "dialog",
             "group",
             "heading",
             "image",
             "label",
             "link",
             "list",
             "list_item",
             "progress",
             "radio",
             "slider",
             "splitter",
             "switch",
             "tab",
             "tab_list",
             "tab_panel",
             "text",
             "textbox",
             "tree",
             "tree_item"
           ]},
        accessibility_label: :accessibility_label,
        accessibility_description: :accessibility_description,
        accessibility_value: :accessibility_value,
        accessibility_selected: :boolean,
        accessibility_expanded: :boolean,
        accessibility_checked: :accessibility_checked,
        accessibility_orientation: {:enum, ["horizontal", "vertical"]},
        accessibility_disabled: :boolean,
        id: :string,
        motion_request: {:default, :non_negative_integer, 0},
        motion_duration: {:default, :positive_integer, 180},
        motion_delay: {:default, :non_negative_integer, 0},
        motion_easing:
          {:default, {:enum, ["linear", "ease_in", "ease_out", "ease_in_out"]}, "ease_out"},
        motion_policy: {:default, {:enum, ["respect_system", "disabled"]}, "respect_system"},
        motion_from_opacity: {:default, :number, 1.0},
        motion_from_x: {:default, :number, 0.0},
        motion_from_y: {:default, :number, 0.0}
      ],
      children: false,
      events: [click: :"phx-click", bounds: :"phx-bounds-change"],
      extension: nil,
      kind: :container,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :item
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :required_string,
        buffer: :text_buffer,
        focus_request: {:default, :non_negative_integer, 0},
        disabled: :boolean,
        soft_wrap: :boolean,
        auto_grow: :boolean,
        min_lines: {:default, :positive_integer, 1},
        max_lines: {:default, :positive_integer, 8},
        submit_policy: {:default, {:enum, ["newline", "submit"]}, "newline"},
        show_whitespaces: :boolean,
        tab_size: {:default, :positive_integer, 2},
        hard_tabs: :boolean,
        geometry_ranges: :text_ranges,
        scroll_request: {:default, :non_negative_integer, 0},
        scroll_to: :text_position,
        decorations: :text_decorations,
        style_runs: :text_style_runs,
        inline_projections: :text_inline_projections,
        block_projections: :text_block_projections
      ],
      children: false,
      events: [
        transaction: :"phx-transaction",
        submit: :"phx-submit",
        selection: :"phx-selection-change",
        viewport: :"phx-viewport-change",
        geometry: :"phx-geometry-change",
        range_geometry: :"phx-range-geometry-change",
        hit_test: :"phx-hit-test",
        focus: :"phx-focus",
        blur: :"phx-blur"
      ],
      extension: nil,
      kind: :text_surface,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: true,
      tag: :text_surface
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        value: :string,
        placeholder: :string,
        focus_request: {:default, :non_negative_integer, 0}
      ],
      children: false,
      events: [
        change: :"phx-change",
        keydown: :"phx-keydown",
        keyup: :"phx-keyup",
        focus: :"phx-focus",
        blur: :"phx-blur"
      ],
      extension: nil,
      kind: :input,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :text_input
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [raster: :resource, label: :string],
      children: false,
      events: [],
      extension: nil,
      kind: :image,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :img
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [],
      children: false,
      events: [],
      extension: nil,
      kind: :text,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :text
    }
  ]
  @impl true
  @spec components() :: [GPUI.Schema.Component.t()]
  def components do
    @components
  end
end
