defmodule GPUI.Codegen do
  @moduledoc false

  alias RustQ.Rust
  alias RustQ.Rust.AST
  alias RustQ.Rust.AST.Builder, as: A
  alias RustQ.Rust.AST.TypeBuilder, as: T

  @spec generated_native_element_schema() :: String.t()
  def generated_native_element_schema do
    components = GPUI.ComponentSpec.components()
    elements = GPUI.ComponentSpec.tags()
    style_specs = GPUI.ComponentSpec.style_specs()
    styles = GPUI.ComponentSpec.styles()
    events = GPUI.ComponentSpec.events()
    resource_specs = GPUI.ComponentSpec.resource_specs()
    resources = GPUI.ComponentSpec.resources()

    """
    // This file is generated by RustQ. Do not edit by hand.

    #{generated_string_slice_const(:GPUI_ELEMENT_TAGS, elements)}
    #{generated_string_slice_const(:GPUI_STYLE_ATTRS, styles)}
    #{generated_string_slice_const(:GPUI_EVENT_ATTRS, events)}
    #{generated_string_slice_const(:GPUI_RESOURCE_TYPES, resources)}

    #{generated_component_specs(components)}

    #{generated_style_module(style_specs)}

    #{generated_enum_decl(:GeneratedElementTag, elements ++ [:Unknown])}

    #{generated_string_enum_decoder(:decode_generated_element_tag, :tag, :GeneratedElementTag, elements, :Unknown)}

    #{generated_enum_decl(:GeneratedResourceType, resources ++ [:Unknown])}

    #{generated_string_enum_decoder(:decode_generated_resource_type, :resource_type, :GeneratedResourceType, resources, :Unknown)}

    pub fn generated_event_attr_to_type(attr: &str) -> Option<&'static str> {
        match attr {
    #{rust_event_match_arms(components)}
            _ => None,
        }
    }

    #{generated_component_kind_decoder(components)}

    #{generated_resource_module(resource_specs)}

    #{generated_event_module(components)}

    #{generated_component_module(components)}
    """
  end

  defp generated_style_module(style_specs) do
    """
    #[cfg(feature = "real-gpui")]
    pub(crate) mod generated_styles {
        use super::*;

    #{indent_generated(generated_style_struct(style_specs))}

    #{indent_generated(generated_apply_style_function(style_specs))}

    #{indent_generated(generated_apply_render_style_function(style_specs))}
    }

    #[cfg(feature = "real-gpui")]
    pub(crate) use generated_styles::{apply_generated_render_styles, apply_generated_style_attr, StyleAttrs};
    """
  end

  defp generated_resource_module(resource_specs) do
    """
    #[cfg(feature = "real-gpui")]
    pub(crate) mod generated_resources {
        use super::*;

    #{indent_generated(generated_decoded_resource_structs(resource_specs))}

    #{indent_generated(generated_decode_resource_functions(resource_specs))}
    }

    #[cfg(feature = "real-gpui")]
    pub(crate) use generated_resources::{decode_generated_raster_resource, decode_generated_resource_ref_resource, GeneratedRaster};
    """
  end

  defp generated_event_module(components) do
    """
    #[cfg(feature = "real-gpui")]
    pub(crate) mod generated_events {
        use super::*;

    #{indent_generated(generated_event_applicators(components))}
    }

    #[cfg(feature = "real-gpui")]
    pub(crate) use generated_events::{apply_generated_click_event, apply_generated_input_events};
    """
  end

  defp generated_component_module(components) do
    """
    #[cfg(feature = "real-gpui")]
    pub(crate) mod generated_components {
        use super::*;

    #{indent_generated(generated_decoded_component_structs(components))}

    #{indent_generated(generated_decode_component_functions(components))}

    #{indent_generated(generated_decode_element_dispatch(components))}

    #{indent_generated(generated_primitive_render_contracts(components))}

    #{indent_generated(generated_render_dispatch())}
    }

    #[cfg(feature = "real-gpui")]
    pub(crate) use generated_components::{decode_generated_element_node, render_generated_element_node};
    """
  end

  defp indent_generated(code) do
    code
    |> String.trim_trailing()
    |> String.split("\n")
    |> Enum.map_join("\n", &["    ", &1])
  end

  defp generated_style_struct(style_specs) do
    Rust.struct(:StyleAttrs,
      vis: :crate,
      derive: [:Clone, :Debug, :Default],
      attrs: [~s|cfg(feature = "real-gpui")|],
      fields:
        Enum.map(style_specs, fn spec ->
          Rust.field(spec.field, rust_style_type(spec.type), vis: :crate)
        end)
    )
    |> Rust.to_fragment()
  end

  defp rust_style_type({:atom_eq, _expected}), do: "bool"
  defp rust_style_type(:atom_string), do: "Option<String>"
  defp rust_style_type(:rgb), do: "Option<u32>"
  defp rust_style_type(:px), do: "Option<f32>"
  defp rust_style_type(:radius), do: "Option<f32>"

  defp generated_decoded_resource_structs(resource_specs) do
    resource_specs
    |> Enum.map_join("\n\n", fn resource ->
      resource.name
      |> generated_resource_struct_name()
      |> Rust.struct(
        vis: :crate,
        derive: [:Clone, :Debug],
        attrs: [~s|cfg(feature = "real-gpui")|, "allow(dead_code)"],
        fields:
          Enum.map(resource.fields, fn {field, type} ->
            Rust.field(rust_field_name(field), rust_resource_type(type), vis: :crate)
          end)
      )
      |> Rust.to_fragment()
    end)
  end

  defp generated_decode_resource_functions(resource_specs) do
    resource_specs
    |> Enum.map_join("\n\n", fn resource ->
      struct_name = generated_resource_struct_name(resource.name)
      function_name = "decode_generated_#{resource.name}_resource"

      function_name
      |> Rust.fn_(
        vis: :crate,
        attrs: [~s|cfg(feature = "real-gpui")|, "allow(dead_code)"],
        args: [{:term, "Term"}],
        returns: "NifResult<#{struct_name}>",
        body: generated_decode_resource_body(resource, struct_name)
      )
      |> Rust.to_fragment()
    end)
  end

  defp generated_decode_resource_body(%{name: :raster}, struct_name) do
    rust_template!("decode_resource_raster.rs", %{"__STRUCT_NAME__" => struct_name})
  end

  defp generated_decode_resource_body(%{name: :resource_ref}, struct_name) do
    rust_template!("decode_resource_ref.rs", %{"__STRUCT_NAME__" => struct_name})
  end

  defp rust_field_name(:type), do: :type_
  defp rust_field_name(field), do: field

  defp rust_resource_type(:u32), do: "u32"
  defp rust_resource_type(:string), do: "String"
  defp rust_resource_type(:binary), do: "Vec<u8>"

  defp rust_resource_type(:atom), do: "String"
  defp rust_resource_type({:option, :u32}), do: "Option<u32>"

  defp generated_resource_struct_name(name), do: "Generated#{Macro.camelize(to_string(name))}"

  defp generated_decoded_component_structs(components) do
    components
    |> Enum.map_join("\n\n", fn component ->
      component.tag
      |> generated_struct_name()
      |> Rust.struct(
        vis: :crate,
        derive: [:Clone, :Debug],
        attrs: [~s|cfg(feature = "real-gpui")|],
        fields: generated_struct_fields(component)
      )
      |> Rust.to_fragment()
    end)
  end

  defp generated_struct_fields(%{kind: :container}) do
    [
      Rust.field(:style, "StyleAttrs", vis: :crate),
      Rust.field(:children, "Vec<ElementNode>", vis: :crate),
      Rust.field(:click, "Option<String>", vis: :crate)
    ]
  end

  defp generated_struct_fields(%{kind: :input}) do
    [
      Rust.field(:style, "StyleAttrs", vis: :crate),
      Rust.field(:value, "String", vis: :crate),
      Rust.field(:placeholder, "Option<String>", vis: :crate),
      Rust.field(:change, "Option<String>", vis: :crate),
      Rust.field(:keydown, "Option<String>", vis: :crate),
      Rust.field(:keyup, "Option<String>", vis: :crate)
    ]
  end

  defp generated_struct_fields(%{kind: :image}) do
    [Rust.field(:raster, "ImageData", vis: :crate)]
  end

  defp generated_struct_fields(%{kind: :text}) do
    [Rust.field(:text, "String", vis: :crate)]
  end

  defp generated_decode_component_functions(components) do
    components
    |> Enum.map_join("\n\n", fn component ->
      struct_name = generated_struct_name(component.tag)
      function_name = "decode_generated_#{component.tag}"

      function_name
      |> Rust.fn_(
        vis: :crate,
        attrs: [~s|cfg(feature = "real-gpui")|],
        args: [{:term, "Term"}],
        returns: "NifResult<#{struct_name}>",
        body: generated_decode_body(component, struct_name)
      )
      |> Rust.to_fragment()
    end)
  end

  defp generated_decode_body(%{kind: :container, events: events}, struct_name) do
    rust_template!("decode_component_container.rs", %{
      "__STRUCT_NAME__" => struct_name,
      "__CLICK_ATTR__" => to_string(Keyword.get(events, :click, :"phx-click"))
    })
  end

  defp generated_decode_body(%{kind: :input, events: events}, struct_name) do
    rust_template!("decode_component_input.rs", %{
      "__STRUCT_NAME__" => struct_name,
      "__CHANGE_ATTR__" => to_string(Keyword.fetch!(events, :change)),
      "__KEYDOWN_ATTR__" => to_string(Keyword.fetch!(events, :keydown)),
      "__KEYUP_ATTR__" => to_string(Keyword.fetch!(events, :keyup))
    })
  end

  defp generated_decode_body(%{kind: :image}, struct_name) do
    rust_template!("decode_component_image.rs", %{"__STRUCT_NAME__" => struct_name})
  end

  defp generated_decode_body(%{kind: :text}, struct_name) do
    rust_template!("decode_component_text.rs", %{"__STRUCT_NAME__" => struct_name})
  end

  defp generated_decode_element_dispatch(components) do
    Rust.fn_(:decode_generated_element_node,
      vis: :crate,
      attrs: [~s|cfg(feature = "real-gpui")|],
      args: [{:tag, "GeneratedElementTag"}, {:term, "Term"}],
      returns: "NifResult<ElementNode>",
      body:
        rust_template!("generated_decode_element.rs", %{
          "__GPUI_DECODE_ELEMENT_ARMS__" => rust_decode_element_arms(components)
        })
    )
    |> Rust.to_fragment()
  end

  defp rust_decode_element_arms(components) do
    Enum.map_join(components, "\n", fn component ->
      variant = rust_variant(component.tag)
      decoder = "decode_generated_#{component.tag}"
      rust_decode_element_arm(component.kind, variant, decoder)
    end)
  end

  defp rust_decode_element_arm(:container, variant, decoder) do
    rust_arm(
      "GeneratedElementTag::#{variant}",
      "#{decoder}(term).map(|node| ElementNode::Div { tag: GeneratedElementTag::#{variant}, style: node.style, children: node.children, click: node.click })"
    )
  end

  defp rust_decode_element_arm(:input, variant, decoder) do
    rust_arm(
      "GeneratedElementTag::#{variant}",
      "#{decoder}(term).map(|node| ElementNode::Input { style: node.style, value: node.value, placeholder: node.placeholder, change: node.change, keydown: node.keydown, keyup: node.keyup })"
    )
  end

  defp rust_decode_element_arm(:image, variant, decoder) do
    rust_arm(
      "GeneratedElementTag::#{variant}",
      "#{decoder}(term).map(|node| ElementNode::Image(node.raster))"
    )
  end

  defp rust_decode_element_arm(:text, variant, decoder) do
    rust_arm(
      "GeneratedElementTag::#{variant}",
      "#{decoder}(term).map(|node| ElementNode::Text(node.text))"
    )
  end

  defp generated_apply_render_style_function(style_specs) do
    Rust.fn_(:apply_generated_render_styles,
      vis: :crate,
      attrs: [~s|cfg(feature = "real-gpui")|],
      args: [{:element, "gpui::Div"}, {:style, "StyleAttrs"}],
      returns: "gpui::Div",
      body:
        rust_template!("generated_style_render.rs", %{
          "__GPUI_STYLE_RENDER_STATEMENTS__" => rust_render_style_statements(style_specs)
        })
    )
    |> Rust.to_fragment()
  end

  defp rust_render_style_statements(style_specs) do
    style_specs
    |> Enum.reject(&is_nil(&1.render))
    |> Enum.map_join("\n", &rust_render_style_statement/1)
  end

  defp rust_render_style_statement(%{field: field, render: :flex_if_true}) do
    """
        if style.#{field} {
            element = element.flex();
        }
    """
  end

  defp rust_render_style_statement(%{field: field, render: {:enum_methods, values}}) do
    arms =
      values
      |> Enum.map_join("\n", fn {value, method} ->
        rust_arm(~s|Some("#{value}")|, "element = element.#{method}()")
      end)

    """
        match style.#{field}.as_deref() {
    #{arms}
            _ => {}
        }
    """
  end

  defp rust_render_style_statement(%{field: field, render: {:option_method, method, :rgb}}) do
    """
        if let Some(value) = style.#{field} {
            element = element.#{method}(rgb(value));
        }
    """
  end

  defp rust_render_style_statement(%{field: field, render: {:option_method, method, :px}}) do
    """
        if let Some(value) = style.#{field} {
            element = element.#{method}(px(value));
        }
    """
  end

  defp generated_event_applicators(_components) do
    rust_template!("generated_events.rs")
  end

  defp generated_primitive_render_contracts(_components) do
    rust_template!("generated_component_contracts.rs")
  end

  defp generated_render_dispatch do
    Rust.fn_(:render_generated_element_node,
      vis: :crate,
      attrs: [~s|cfg(feature = "real-gpui")|],
      args: [
        {:node, "ElementNode"},
        {:runtime, "ResourceArc<RuntimeResource>"},
        {:window_id, "u64"},
        {:input_entities, "&mut HashMap<String, gpui::Entity<NativeTextInput>>"},
        {:cx, "&mut gpui::Context<ElixirRoot>"}
      ],
      returns: "gpui::AnyElement",
      body: rust_template!("generated_render_dispatch.rs")
    )
    |> Rust.to_fragment()
  end

  defp generated_apply_style_function(style_specs) do
    Rust.fn_(:apply_generated_style_attr,
      vis: :crate,
      attrs: [~s|cfg(feature = "real-gpui")|],
      args: [{:attrs, "&mut StyleAttrs"}, {:key, "&str"}, {:value, "Term"}],
      body:
        rust_template!("generated_style_apply.rs", %{
          "__GPUI_STYLE_APPLY_ARMS__" => rust_style_apply_arms(style_specs)
        })
    )
    |> Rust.to_fragment()
  end

  defp rust_style_apply_arms(style_specs) do
    Enum.map_join(style_specs, "\n", fn spec ->
      rust_arm(~s|"#{spec.name}"|, rust_style_assignment(spec.field, spec.type))
    end)
  end

  defp rust_style_assignment(field, {:atom_eq, expected}) do
    "attrs.#{field} = atom_eq(value, \"#{expected}\")"
  end

  defp rust_style_assignment(field, :atom_string), do: "attrs.#{field} = atom_string(value)"
  defp rust_style_assignment(field, :rgb), do: "attrs.#{field} = rgb_value(value)"
  defp rust_style_assignment(field, :px), do: "attrs.#{field} = px_value(value)"
  defp rust_style_assignment(field, :radius), do: "attrs.#{field} = radius_value(value)"

  defp generated_struct_name(tag), do: "Generated#{Macro.camelize(to_string(tag))}"

  defp generated_component_specs(components) do
    kinds = components |> Enum.map(& &1.kind) |> Enum.uniq()
    generated_enum_decl(:GeneratedComponentKind, kinds ++ [:Unknown])
  end

  defp rust_event_match_arms(components) do
    components
    |> Enum.flat_map(& &1.events)
    |> Enum.uniq_by(fn {_event_type, attr} -> attr end)
    |> Enum.map_join("\n", fn {event_type, attr} ->
      rust_arm(~s|"#{attr}"|, ~s|Some("#{event_type}")|)
    end)
  end

  defp generated_component_kind_decoder(components) do
    arms =
      Enum.map(components, fn component ->
        %AST.Arm{
          pattern: %AST.PatPath{path: A.path([:GeneratedElementTag, rust_variant(component.tag)])},
          body: [A.return_stmt(A.path([:GeneratedComponentKind, rust_variant(component.kind)]))]
        }
      end) ++
        [
          %AST.Arm{
            pattern: %AST.PatPath{path: A.path([:GeneratedElementTag, :Unknown])},
            body: [A.return_stmt(A.path([:GeneratedComponentKind, :Unknown]))]
          }
        ]

    %AST.Function{
      name: :generated_component_kind,
      vis: :pub,
      args: [A.arg(:tag, T.path(:GeneratedElementTag))],
      returns: T.path(:GeneratedComponentKind),
      body: [A.return_stmt(%AST.Match{expr: A.var(:tag), arms: arms})]
    }
    |> RustQ.Rust.AST.Render.render_item()
  end

  defp rust_template!(name, replacements \\ %{}) do
    source =
      [__DIR__, "..", "..", "priv", "rustq", "native", name]
      |> Path.join()
      |> Path.expand()
      |> File.read!()

    Enum.reduce(replacements, source, fn {placeholder, replacement}, source ->
      String.replace(source, placeholder, replacement)
    end)
  end

  defp generated_string_slice_const(name, values) do
    Rust.const(
      name,
      T.ref(T.slice(T.ref(:str))),
      values |> Enum.map(&to_string/1) |> A.slice() |> render_expr(),
      vis: :pub
    )
    |> Rust.to_fragment()
  end

  defp generated_enum_decl(name, variants) do
    Rust.enum(name,
      derive: [:Clone, :Copy, :Debug, :Eq, :PartialEq],
      variants: Enum.map(variants, &rust_variant/1),
      vis: :pub
    )
    |> Rust.to_fragment()
  end

  defp generated_string_enum_decoder(name, arg_name, enum_name, values, unknown) do
    arms =
      Enum.map(values, fn value ->
        %AST.Arm{
          pattern: %AST.PatLiteral{value: to_string(value)},
          body: [A.return_stmt(A.path([enum_name, rust_variant(value)]))]
        }
      end) ++
        [
          %AST.Arm{
            pattern: A.wildcard(),
            body: [A.return_stmt(A.path([enum_name, rust_variant(unknown)]))]
          }
        ]

    %AST.Function{
      name: name,
      vis: :pub,
      args: [A.arg(arg_name, T.ref(:str))],
      returns: T.path(enum_name),
      body: [A.return_stmt(%AST.Match{expr: A.var(arg_name), arms: arms})]
    }
    |> RustQ.Rust.AST.Render.render_item()
  end

  defp render_expr(expr), do: expr |> RustQ.Rust.AST.Render.render_expr() |> IO.iodata_to_binary()

  defp rust_arm(pattern, body) do
    pattern
    |> Rust.arm(body)
    |> Rust.to_fragment()
  end

  defp rust_variant(value), do: value |> Atom.to_string() |> Macro.camelize()
end
