defmodule GPUI.Codegen.Native.Schema do
  @moduledoc false

  alias GPUI.Codegen.Native.Style
  alias RustQ.Rust.AST
  alias RustQ.Rust.AST.Builder, as: A
  alias RustQ.Rust.AST.PatternBuilder, as: P
  alias RustQ.Rust.AST.TypeBuilder, as: T

  @spec source() :: String.t()
  def source do
    components = GPUI.Schema.components()
    elements = GPUI.Schema.tags()
    style_specs = GPUI.Schema.style_specs()
    styles = GPUI.Schema.styles()
    events = GPUI.Schema.events()
    resources = GPUI.Schema.resources()

    """
    // This file is generated by RustQ. Do not edit by hand.

    #{generated_string_slice_const(:GPUI_ELEMENT_TAGS, elements)}
    #{generated_string_slice_const(:GPUI_STYLE_ATTRS, styles)}
    #{generated_string_slice_const(:GPUI_EVENT_ATTRS, events)}
    #{generated_string_slice_const(:GPUI_RESOURCE_TYPES, resources)}

    #{generated_component_specs(components)}

    #{Style.source(style_specs)}

    #{generated_enum_decl(:GeneratedElementTag, elements ++ [:Unknown])}

    #{generated_string_enum_decoder(:decode_generated_element_tag, :tag, :GeneratedElementTag, elements, :Unknown)}

    #{generated_enum_decl(:GeneratedResourceType, resources ++ [:Unknown])}

    #{generated_string_enum_decoder(:decode_generated_resource_type, :resource_type, :GeneratedResourceType, resources, :Unknown)}

    #{generated_event_attr_function(components)}

    #{generated_component_kind_function(components)}
    """
  end

  defp generated_component_specs(components) do
    kinds = components |> Enum.map(& &1.kind) |> Enum.uniq()
    generated_enum_decl(:GeneratedComponentKind, kinds ++ [:Unknown])
  end

  defp generated_event_attr_function(components) do
    arms =
      components
      |> Enum.flat_map(& &1.events)
      |> Enum.uniq_by(fn {_event_type, attr} -> attr end)
      |> Enum.map(fn {event_type, attr} ->
        %AST.Arm{
          pattern: P.lit(to_string(attr)),
          body: [A.return_stmt(A.some(A.lit(to_string(event_type))))]
        }
      end)
      |> Kernel.++([%AST.Arm{pattern: P.wildcard(), body: [A.return_stmt(A.none())]}])

    %AST.Function{
      name: :generated_event_attr_to_type,
      vis: :pub,
      args: [A.arg(:attr, "&str")],
      returns: "Option<&'static str>",
      body: [A.return_stmt(A.match_expr(A.var(:attr), arms))]
    }
    |> render_item()
  end

  defp generated_component_kind_function(components) do
    arms =
      Enum.map(components, fn component ->
        %AST.Arm{
          pattern: P.path([:GeneratedElementTag, rust_variant(component.tag)]),
          body: [
            A.return_stmt(A.path([:GeneratedComponentKind, rust_variant(component.kind)]))
          ]
        }
      end) ++
        [
          %AST.Arm{
            pattern: P.path([:GeneratedElementTag, :Unknown]),
            body: [A.return_stmt(A.path([:GeneratedComponentKind, :Unknown]))]
          }
        ]

    %AST.Function{
      name: :generated_component_kind,
      vis: :pub,
      args: [A.arg(:tag, "GeneratedElementTag")],
      returns: "GeneratedComponentKind",
      body: [A.return_stmt(A.match_expr(A.var(:tag), arms))]
    }
    |> render_item()
  end

  defp generated_string_slice_const(name, values) do
    %AST.Const{
      name: name,
      type: T.ref(T.slice(T.ref(:str))),
      expr: values |> Enum.map(&to_string/1) |> A.slice(),
      vis: :pub
    }
    |> render_item()
  end

  defp generated_enum_decl(name, variants) do
    %AST.Enum{
      name: name,
      derive: [:Clone, :Copy, :Debug, :Eq, :PartialEq],
      variants: Enum.map(variants, &%AST.EnumVariant{name: rust_variant(&1)}),
      vis: :pub
    }
    |> render_item()
  end

  defp generated_string_enum_decoder(name, arg_name, enum_name, values, unknown) do
    arms =
      Enum.map(values, fn value ->
        %AST.Arm{
          pattern: %AST.PatLiteral{value: to_string(value)},
          body: [A.return_stmt(A.path([enum_name, rust_variant(value)]))]
        }
      end) ++
        [
          %AST.Arm{
            pattern: A.wildcard(),
            body: [A.return_stmt(A.path([enum_name, rust_variant(unknown)]))]
          }
        ]

    %AST.Function{
      name: name,
      vis: :pub,
      args: [A.arg(arg_name, T.ref(:str))],
      returns: T.path(enum_name),
      body: [A.return_stmt(%AST.Match{expr: A.var(arg_name), arms: arms})]
    }
    |> render_item()
  end

  defp render_item(item), do: RustQ.Rust.AST.Render.render_item(item)

  defp rust_variant(value),
    do: value |> Atom.to_string() |> Macro.camelize() |> RustQ.Atom.identifier!()
end
