defmodule GPUI.Codegen.Native.Schema do
  @moduledoc false

  alias GPUI.Codegen.Native.Decoder
  alias GPUI.Codegen.Native.Style
  alias RustQ.Rust.AST
  alias RustQ.Rust.AST.Builder, as: A
  alias RustQ.Rust.AST.PatternBuilder, as: P
  alias RustQ.Rust.AST.TypeBuilder, as: T

  @spec source() :: String.t()
  def source do
    components = GPUI.Schema.components()
    elements = GPUI.Schema.tags()
    style_specs = GPUI.Schema.style_specs()

    [
      "// This file is generated by RustQ. Do not edit by hand.",
      generated_component_specs(components),
      generated_decoder_helpers(),
      Style.source(style_specs),
      generated_enum_decl(:GeneratedElementTag, elements ++ [:Unknown]),
      generated_string_enum_decoder(
        :decode_generated_element_tag,
        :tag,
        :GeneratedElementTag,
        elements,
        :Unknown
      ),
      generated_component_kind_function(components)
    ]
    |> Enum.join("\n\n")
    |> Kernel.<>("\n")
  end

  defp generated_decoder_helpers do
    Enum.map_join(Decoder.asts(), "\n\n", &render_item/1)
  end

  defp generated_component_specs(components) do
    kinds = components |> Enum.map(& &1.kind) |> Enum.uniq()
    generated_enum_decl(:GeneratedComponentKind, kinds ++ [:Unknown])
  end

  defp generated_component_kind_function(components) do
    arms =
      Enum.map(components, fn component ->
        %AST.Arm{
          pattern: P.path([:GeneratedElementTag, rust_variant(component.tag)]),
          body: [
            A.return_stmt(A.path([:GeneratedComponentKind, rust_variant(component.kind)]))
          ]
        }
      end) ++
        [
          %AST.Arm{
            pattern: P.path([:GeneratedElementTag, :Unknown]),
            body: [A.return_stmt(A.path([:GeneratedComponentKind, :Unknown]))]
          }
        ]

    %AST.Function{
      name: :generated_component_kind,
      vis: :pub,
      args: [A.arg(:tag, "GeneratedElementTag")],
      returns: "GeneratedComponentKind",
      body: [A.return_stmt(A.match_expr(A.var(:tag), arms))]
    }
    |> render_item()
  end

  defp generated_enum_decl(name, variants) do
    %AST.Enum{
      name: name,
      derive: [:Clone, :Copy, :Debug, :Eq, :PartialEq],
      variants: Enum.map(variants, &%AST.EnumVariant{name: rust_variant(&1)}),
      vis: :pub
    }
    |> render_item()
  end

  defp generated_string_enum_decoder(name, arg_name, enum_name, values, unknown) do
    arms =
      Enum.map(values, fn value ->
        %AST.Arm{
          pattern: %AST.PatLiteral{value: to_string(value)},
          body: [A.return_stmt(A.path([enum_name, rust_variant(value)]))]
        }
      end) ++
        [
          %AST.Arm{
            pattern: A.wildcard(),
            body: [A.return_stmt(A.path([enum_name, rust_variant(unknown)]))]
          }
        ]

    %AST.Function{
      name: name,
      vis: :pub,
      args: [A.arg(arg_name, T.ref(:str))],
      returns: T.path(enum_name),
      body: [A.return_stmt(%AST.Match{expr: A.var(arg_name), arms: arms})]
    }
    |> render_item()
  end

  defp render_item(item), do: RustQ.Rust.AST.Render.render_item(item)

  defp rust_variant(value),
    do: value |> Atom.to_string() |> Macro.camelize() |> RustQ.Atom.identifier!()
end
