// This file is generated by RustQ. Do not edit by hand.

pub struct OpenWindowCommand<'a> {
    pub title: &'a Term,
    pub size: &'a Term,
    pub root: &'a Term,
}

pub fn decode_open_window<'a>(payload: &'a Term) -> Result<OpenWindowCommand<'a>, String> {
    Ok(OpenWindowCommand {
        title: required_payload(payload, "title")?,
        size: required_payload(payload, "size")?,
        root: required_payload(payload, "root")?,
    })
}


pub struct CloseWindowCommand<'a> {
    pub window_id: &'a Term,
}

pub fn decode_close_window<'a>(payload: &'a Term) -> Result<CloseWindowCommand<'a>, String> {
    Ok(CloseWindowCommand {
        window_id: required_payload(payload, "window_id")?,
    })
}


pub struct UpdateViewCommand<'a> {
    pub view_id: &'a Term,
    pub tree: &'a Term,
}

pub fn decode_update_view<'a>(payload: &'a Term) -> Result<UpdateViewCommand<'a>, String> {
    Ok(UpdateViewCommand {
        view_id: required_payload(payload, "view_id")?,
        tree: required_payload(payload, "tree")?,
    })
}


pub fn dispatch_host_command(op: &str, payload: &Term) -> Term {
    match op {
        "ping" => handle_ping(),
        "shutdown" => handle_shutdown(),
        "open_window" => match decode_open_window(payload) { Ok(command) => handle_open_window(command), Err(reason) => error_reply(reason) },
        "close_window" => match decode_close_window(payload) { Ok(command) => handle_close_window(command), Err(reason) => error_reply(reason) },
        "update_view" => match decode_update_view(payload) { Ok(command) => handle_update_view(command), Err(reason) => error_reply(reason) },
        _ => error_reply(format!("unsupported_op:{op}")),
    }
}
