// This file is generated by RustQ. Do not edit by hand.

#[rustler::nif]
fn start_runtime<'a>(env: Env<'a>) -> NifResult<Term<'a>> {
    start_runtime_impl(env)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn open_window<'a>(
    env: Env<'a>,
    runtime: ResourceArc<RuntimeResource>,
    window: Term<'a>,
) -> NifResult<Term<'a>> {
    open_window_impl(env, runtime, window)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn update_window<'a>(
    env: Env<'a>,
    runtime: ResourceArc<RuntimeResource>,
    window_id: u64,
    tree: Term<'a>,
) -> NifResult<Term<'a>> {
    update_window_impl(env, runtime, window_id, tree)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn put_resource<'a>(
    env: Env<'a>,
    runtime: ResourceArc<RuntimeResource>,
    resource_id: String,
    resource: Term<'a>,
) -> NifResult<Term<'a>> {
    put_resource_impl(env, runtime, resource_id, resource)
}
#[rustler::nif]
fn drop_resource<'a>(
    env: Env<'a>,
    runtime: ResourceArc<RuntimeResource>,
    resource_id: String,
) -> NifResult<Term<'a>> {
    drop_resource_impl(env, runtime, resource_id)
}
#[rustler::nif]
fn drain_events<'a>(
    env: Env<'a>,
    runtime: ResourceArc<RuntimeResource>,
) -> NifResult<Term<'a>> {
    drain_events_impl(env, runtime)
}
#[rustler::nif]
fn emit_test_event<'a>(
    env: Env<'a>,
    runtime: ResourceArc<RuntimeResource>,
    event: Term<'a>,
) -> NifResult<Term<'a>> {
    emit_test_event_impl(env, runtime, event)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn validate_tree<'a>(env: Env<'a>, tree: Term<'a>) -> NifResult<Term<'a>> {
    validate_tree_impl(env, tree)
}
