defmodule GPUI.Components.Schema.Declarations do
  @moduledoc "Conventional native component declarations."
  @behaviour GPUI.Schema.Provider
  @components [
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [id: :required_string],
      children: true,
      events: [
        drag_enter: :"phx-drag-enter",
        drag_move: :"phx-drag-move",
        drag_leave: :"phx-drag-leave",
        drop: :"phx-drop"
      ],
      extension: nil,
      kind: :drop_target_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: true,
      tag: :ui_drop_target
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        orientation: {:default, {:enum, ["horizontal", "vertical"]}, "horizontal"},
        sizes: :number_pair,
        min_sizes: {:default, :number_pair, [100.0, 100.0]},
        max_sizes: {:default, :number_pair, [100_000.0, 100_000.0]},
        resize_request: {:default, :non_negative_integer, 0}
      ],
      children: true,
      events: [change: :"phx-change"],
      extension: nil,
      kind: :split_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [:"phx-change"],
      stateful: true,
      tag: :ui_split
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :required_string,
        clipboard_text: :string,
        file_prompt: :string,
        file_max_bytes: {:default, :positive_integer, 10_485_760},
        variant:
          {:enum,
           [
             "default",
             "primary",
             "secondary",
             "danger",
             "warning",
             "success",
             "info",
             "ghost",
             "link",
             "text"
           ]},
        size: {:enum, ["xs", "sm", "md", "lg"]},
        disabled: :boolean,
        selected: :boolean,
        loading: :boolean,
        outline: :boolean,
        compact: :boolean
      ],
      children: true,
      events: [
        click: :"phx-click",
        clipboard: :"phx-clipboard-read",
        clipboard_write: :"phx-clipboard-write",
        file_read: :"phx-file-read"
      ],
      extension: nil,
      kind: :button_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_button
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :string,
        value: {:default, :number, 0.0},
        max: {:default, :positive_number, 100.0},
        indeterminate: :boolean
      ],
      children: false,
      events: [],
      extension: nil,
      kind: :progress_component,
      public_hidden_attrs: [],
      public_required_attrs: [:label],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_progress
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :required_string,
        open: :boolean,
        anchor:
          {:default,
           {:enum,
            [
              "top_left",
              "top_center",
              "top_right",
              "bottom_left",
              "bottom_center",
              "bottom_right",
              "left_center",
              "right_center"
            ]}, "top_left"},
        appearance: {:default, :boolean, true},
        closable: {:default, :boolean, true}
      ],
      children: true,
      events: [change: :"phx-change"],
      extension: nil,
      kind: :popover_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [trigger: :required, content: :required],
      required_events: [],
      stateful: true,
      tag: :ui_popover
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [],
      children: true,
      events: [],
      extension: nil,
      kind: :popover_trigger_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_popover_trigger
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [],
      children: true,
      events: [],
      extension: nil,
      kind: :popover_content_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_popover_content
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        text: {:default, :string},
        delay: {:default, :number, 500.0},
        hoverable: :boolean
      ],
      children: true,
      events: [],
      extension: nil,
      kind: :tooltip_component,
      public_hidden_attrs: [:text],
      public_required_attrs: [],
      public_slots: [trigger: :required, content: :required],
      required_events: [],
      stateful: false,
      tag: :ui_tooltip
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [],
      children: true,
      events: [],
      extension: nil,
      kind: :tooltip_trigger_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_tooltip_trigger
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        open: :boolean,
        title: :required_string,
        width: {:default, :number, 448.0},
        overlay: {:default, :boolean, true},
        closable: {:default, :boolean, true},
        keyboard: {:default, :boolean, true},
        close_button: {:default, :boolean, true}
      ],
      children: true,
      events: [change: :"phx-change"],
      extension: nil,
      kind: :dialog_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [trigger: :optional, content: :required],
      required_events: [],
      stateful: true,
      tag: :ui_dialog
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [],
      children: true,
      events: [],
      extension: nil,
      kind: :dialog_trigger_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_dialog_trigger
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [],
      children: true,
      events: [],
      extension: nil,
      kind: :dialog_content_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_dialog_content
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :required_string,
        open: :boolean,
        anchor:
          {:default,
           {:enum,
            [
              "top_left",
              "top_center",
              "top_right",
              "bottom_left",
              "bottom_center",
              "bottom_right",
              "left_center",
              "right_center"
            ]}, "top_left"},
        disabled: :boolean
      ],
      children: true,
      events: [change: :"phx-change", select: :"phx-select"],
      extension: nil,
      kind: :dropdown_menu_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [trigger: :required, item: :one_or_more],
      required_events: [],
      stateful: true,
      tag: :ui_dropdown_menu
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [],
      children: true,
      events: [],
      extension: nil,
      kind: :dropdown_menu_trigger_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_dropdown_menu_trigger
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        value: {:default, :string},
        label: {:default, :string},
        disabled: :boolean,
        checked: :boolean
      ],
      children: false,
      events: [],
      extension: nil,
      kind: :dropdown_menu_item_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_dropdown_menu_item
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :required_string,
        size: {:enum, ["xs", "sm", "md", "lg"]},
        checked: :boolean,
        disabled: :boolean
      ],
      children: true,
      events: [change: :"phx-change"],
      extension: nil,
      kind: :checkbox_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [:"phx-change"],
      stateful: false,
      tag: :ui_checkbox
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :required_string,
        value: {:default, :string},
        focus_request: {:default, :non_negative_integer, 0},
        placeholder: :string,
        size: {:enum, ["xs", "sm", "md", "lg"]},
        disabled: :boolean,
        cleanable: :boolean,
        masked: :boolean,
        loading: :boolean
      ],
      children: false,
      events: [
        change: :"phx-change",
        submit: :"phx-submit",
        focus: :"phx-focus",
        blur: :"phx-blur"
      ],
      extension: nil,
      kind: :input_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [:"phx-change"],
      stateful: true,
      tag: :ui_input
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :required_string,
        value: :string,
        options: :select_options,
        placeholder: :string,
        size: {:enum, ["xs", "sm", "md", "lg"]},
        disabled: :boolean,
        cleanable: :boolean
      ],
      children: false,
      events: [change: :"phx-change"],
      extension: nil,
      kind: :select_component,
      public_hidden_attrs: [],
      public_required_attrs: [:options],
      public_slots: [],
      required_events: [:"phx-change"],
      stateful: true,
      tag: :ui_select
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :required_string,
        value: :string,
        options: :select_options,
        placeholder: :string,
        search_placeholder: :string,
        size: {:enum, ["xs", "sm", "md", "lg"]},
        disabled: :boolean,
        cleanable: :boolean,
        loading: :boolean
      ],
      children: false,
      events: [change: :"phx-change", search: :"phx-search"],
      extension: nil,
      kind: :combobox_component,
      public_hidden_attrs: [],
      public_required_attrs: [:options],
      public_slots: [],
      required_events: [:"phx-change"],
      stateful: true,
      tag: :ui_combobox
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        checked: :boolean,
        label: :required_string,
        size: {:enum, ["xs", "sm", "md", "lg"]},
        disabled: :boolean,
        loading: :boolean
      ],
      children: false,
      events: [change: :"phx-change"],
      extension: nil,
      kind: :switch_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [:"phx-change"],
      stateful: false,
      tag: :ui_switch
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :required_string,
        value: :string,
        options: :radio_options,
        orientation: {:enum, ["horizontal", "vertical"]},
        size: {:enum, ["xs", "sm", "md", "lg"]},
        disabled: :boolean
      ],
      children: false,
      events: [change: :"phx-change"],
      extension: nil,
      kind: :radio_group_component,
      public_hidden_attrs: [],
      public_required_attrs: [:value, :options],
      public_slots: [],
      required_events: [:"phx-change"],
      stateful: false,
      tag: :ui_radio_group
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        expanded: :string_list,
        multiple: :boolean,
        bordered: {:default, :boolean, true},
        size: {:enum, ["xs", "sm", "md", "lg"]},
        disabled: :boolean
      ],
      children: true,
      events: [change: :"phx-change"],
      extension: nil,
      kind: :accordion_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [:"phx-change"],
      stateful: false,
      tag: :ui_accordion
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [id: :string, title: :string, disabled: :boolean],
      children: true,
      events: [],
      extension: nil,
      kind: :accordion_item_component,
      public_hidden_attrs: [],
      public_required_attrs: [:title],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_accordion_item
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :string,
        selected: :string,
        selected_index: :non_negative_integer,
        reveal: :string,
        reveal_index: :non_negative_integer,
        reveal_strategy: {:default, {:enum, ["nearest", "top", "center", "bottom"]}, "nearest"},
        total_count: {:default, :non_negative_integer, 0},
        offset: {:default, :non_negative_integer, 0},
        overscan: {:default, :non_negative_integer, 8},
        item_height: {:default, :positive_number, 40.0},
        disabled: :boolean
      ],
      children: true,
      events: [change: :"phx-change", range: :"phx-range"],
      extension: nil,
      kind: :virtual_list_component,
      public_hidden_attrs: [],
      public_required_attrs: [:label],
      public_slots: [],
      required_events: [],
      stateful: true,
      tag: :ui_virtual_list
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [id: :string, disabled: :boolean],
      children: true,
      events: [],
      extension: nil,
      kind: :virtual_list_item_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_virtual_list_item
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :string,
        alignment: {:default, {:enum, ["top", "bottom"]}, "top"},
        overdraw: {:default, :number, 256.0},
        reveal: :string,
        reveal_request: {:default, :non_negative_integer, 0},
        reveal_strategy: {:default, {:enum, ["nearest", "top"]}, "nearest"},
        follow: {:default, {:enum, ["none", "tail"]}, "none"},
        follow_request: {:default, :non_negative_integer, 0}
      ],
      children: true,
      events: [range: :"phx-range"],
      extension: nil,
      kind: :virtual_collection_component,
      public_hidden_attrs: [],
      public_required_attrs: [:label],
      public_slots: [],
      required_events: [],
      stateful: true,
      tag: :ui_virtual_collection
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [id: :string, revision: {:default, :non_negative_integer, 0}],
      children: true,
      events: [],
      extension: nil,
      kind: :virtual_item_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_virtual_item
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :string,
        text: {:default, :string},
        runs: :rich_text_runs,
        selectable: {:default, :boolean, true}
      ],
      children: false,
      events: [link: :"phx-link"],
      extension: nil,
      kind: :rich_text_component,
      public_hidden_attrs: [],
      public_required_attrs: [:label, :text],
      public_slots: [],
      required_events: [],
      stateful: true,
      tag: :ui_rich_text
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :string,
        selected: :string,
        selected_index: :non_negative_integer,
        selected_column: :string,
        reveal: :string,
        reveal_index: :non_negative_integer,
        reveal_strategy: {:default, {:enum, ["nearest", "top", "center", "bottom"]}, "nearest"},
        sort_column: :string,
        sort_direction: {:default, {:enum, ["none", "ascending", "descending"]}, "none"},
        total_count: {:default, :non_negative_integer, 0},
        offset: {:default, :non_negative_integer, 0},
        overscan: {:default, :non_negative_integer, 8},
        item_height: {:default, :positive_number, 44.0},
        header_height: {:default, :positive_number, 40.0},
        disabled: :boolean
      ],
      children: true,
      events: [
        change: :"phx-change",
        cell_change: :"phx-cell-change",
        sort: :"phx-sort",
        range: :"phx-range"
      ],
      extension: nil,
      kind: :data_table_component,
      public_hidden_attrs: [],
      public_required_attrs: [:label],
      public_slots: [],
      required_events: [],
      stateful: true,
      tag: :ui_data_table
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: {:default, :string},
        width: {:default, :positive_number, 160.0},
        align: {:default, {:enum, ["left", "center", "right"]}, "left"},
        sortable: :boolean
      ],
      children: false,
      events: [],
      extension: nil,
      kind: :table_column_component,
      public_hidden_attrs: [],
      public_required_attrs: [:label],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_table_column
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [id: :string, disabled: :boolean],
      children: true,
      events: [],
      extension: nil,
      kind: :table_row_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_table_row
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :string,
        selected: :string,
        selected_index: :non_negative_integer,
        reveal: :string,
        reveal_index: :non_negative_integer,
        reveal_strategy: {:default, {:enum, ["nearest", "top", "center", "bottom"]}, "nearest"},
        total_count: {:default, :non_negative_integer, 0},
        offset: {:default, :non_negative_integer, 0},
        overscan: {:default, :non_negative_integer, 8},
        item_height: {:default, :positive_number, 40.0},
        disabled: :boolean
      ],
      children: true,
      events: [change: :"phx-change", toggle: :"phx-toggle", range: :"phx-range"],
      extension: nil,
      kind: :tree_component,
      public_hidden_attrs: [],
      public_required_attrs: [:label],
      public_slots: [],
      required_events: [],
      stateful: true,
      tag: :ui_tree
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        parent_id: :string,
        level: {:default, :positive_integer, 1},
        branch: :boolean,
        expanded: :boolean,
        position: :positive_integer,
        set_size: :positive_integer,
        disabled: :boolean
      ],
      children: true,
      events: [],
      extension: nil,
      kind: :tree_item_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_tree_item
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :string,
        mode: {:default, {:enum, ["plain", "diff"]}, "plain"},
        selected: :string,
        selected_index: :non_negative_integer,
        reveal: :string,
        reveal_index: :non_negative_integer,
        reveal_strategy: {:default, {:enum, ["nearest", "top", "center", "bottom"]}, "nearest"},
        total_count: {:default, :non_negative_integer, 0},
        offset: {:default, :non_negative_integer, 0},
        overscan: {:default, :non_negative_integer, 12},
        item_height: {:default, :positive_number, 24.0},
        max_columns: {:default, :non_negative_integer, 0},
        tab_width: {:default, :positive_integer, 4},
        show_line_numbers: {:default, :boolean, true},
        disabled: :boolean
      ],
      children: true,
      events: [change: :"phx-change", range: :"phx-range", click: :"phx-copy"],
      extension: nil,
      kind: :code_viewer_component,
      public_hidden_attrs: [],
      public_required_attrs: [:label],
      public_slots: [],
      required_events: [],
      stateful: true,
      tag: :ui_code_viewer
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        text: {:default, :string},
        number: :non_negative_integer,
        kind:
          {:default,
           {:enum,
            ["context", "addition", "deletion", "hunk", "debug", "info", "warning", "error"]},
           "context"},
        disabled: :boolean
      ],
      children: false,
      events: [],
      extension: nil,
      kind: :code_line_component,
      public_hidden_attrs: [],
      public_required_attrs: [:text],
      public_slots: [],
      required_events: [],
      stateful: false,
      tag: :ui_code_line
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        value: :string,
        options: :select_options,
        variant: {:enum, ["tab", "outline", "pill", "segmented", "underline"]},
        size: {:enum, ["xs", "sm", "md", "lg"]},
        disabled: :boolean,
        menu: :boolean
      ],
      children: false,
      events: [change: :"phx-change"],
      extension: nil,
      kind: :tabs_component,
      public_hidden_attrs: [],
      public_required_attrs: [:value, :options],
      public_slots: [],
      required_events: [:"phx-change"],
      stateful: false,
      tag: :ui_tabs
    },
    %{
      __struct__: GPUI.Schema.Component,
      attrs: [
        id: :string,
        label: :required_string,
        value: {:default, :number, 0.0},
        min: {:default, :number, 0.0},
        max: {:default, :number, 100.0},
        step: {:default, :number, 1.0},
        orientation: {:default, {:enum, ["horizontal", "vertical"]}, "horizontal"},
        scale: {:default, {:enum, ["linear", "logarithmic"]}, "linear"},
        disabled: :boolean,
        reverse: :boolean
      ],
      children: false,
      events: [change: :"phx-change", release: :"phx-release"],
      extension: nil,
      kind: :slider_component,
      public_hidden_attrs: [],
      public_required_attrs: [],
      public_slots: [],
      required_events: [:"phx-change"],
      stateful: true,
      tag: :ui_slider
    }
  ]
  @impl true
  @spec components() :: [GPUI.Schema.Component.t()]
  def components do
    @components
  end
end
