[package]
name = "gpui_components"
version = "0.1.1"
edition = "2021"
license = "MIT"
publish = false

[features]
default = []
native-render = ["dep:zed_gpui", "dep:gpui-component", "gpui_core/native-render"]

[lib]
name = "gpui_components"
crate-type = ["rlib"]

[dependencies]
gpui_core = { path = "../../gpui/native" }
gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "5c5eb1db04dc1146bdec903a8ac74407bd6c2098", optional = true }
zed_gpui = { git = "https://github.com/zed-industries/zed", package = "gpui", optional = true }
